package schemix

import (
	"fmt"

	"github.com/warpstreamlabs/bento/public/bloblang"
	"go.opentelemetry.io/otel/trace"
)

// defaultMaxSchemaDepth bounds construction-time schema analysis when the caller
// does not configure a limit.
//
// CUE permits mutually recursive definitions, which expand without end:
//
//	#A: {bs: [...#B]}
//	#B: {as: [...#A]}
//
// Since a schema is untrusted input wherever users can supply it, every
// recursive walk performed by New() carries this bound.
const defaultMaxSchemaDepth = 32

// Option configures a Validator during construction.
type Option func(*validatorConfig)

// validatorConfig holds optional configuration for Validator construction.
type validatorConfig struct {
	errorFormatter       ErrorFormatter
	localizer            Localizer // default for Result.LocalizedMessages (nil = EnUS)
	customFuncs          []customFuncEntry
	funcMapErr           error                // propagated from FuncMap validation
	allowMethodOverrides []string             // built-in method names allowed to be overridden
	allowFuncOverrides   []string             // built-in function names allowed to be overridden
	overrideAll          bool                 // disable all conflict checks
	metricsRecorder      MetricsRecorder      // optional observability hook (nil = zero overhead)
	schemaName           string               // optional name for observability labels
	tracerProvider       trace.TracerProvider // optional OTel tracer provider (nil = no tracing)
	maxSchemaDepth       int                  // bound on construction-time schema recursion
	maxSchemaDepthSet    bool                 // distinguishes an explicit 0 from an unset limit
}

// customFuncEntry stores one custom function/method registration.
type customFuncEntry struct {
	name string
	kind customFuncKind
	// V1 style (simple)
	funcV1   bloblang.FunctionConstructor
	methodV1 bloblang.MethodConstructor
	// V2 style (with PluginSpec)
	spec     *bloblang.PluginSpec
	funcV2   bloblang.FunctionConstructorV2
	methodV2 bloblang.MethodConstructorV2
}

type customFuncKind int

const (
	kindFuncV1   customFuncKind = iota // RegisterFunction
	kindFuncV2                         // RegisterFunctionV2
	kindMethodV1                       // RegisterMethod
	kindMethodV2                       // RegisterMethodV2
)

// WithErrorFormatter sets a custom error message formatter.
// When set, all ValidationError.Message values will be generated by this function
// instead of the default English messages.
//
// This replaces the raw diagnostic, which is the text meant for logs. To change
// what a person reads — including translating it — use WithLocalizer instead.
func WithErrorFormatter(f ErrorFormatter) Option {
	return func(cfg *validatorConfig) {
		cfg.errorFormatter = f
	}
}

// WithLocalizer sets the Localizer that Result.LocalizedMessages uses by
// default, so a single-language service states its language once:
//
//	v := schemix.MustNew(schema, schemix.WithLocalizer(schemix.ZhCN))
//	msgs := v.Process(data).LocalizedMessages()
//
// It is a default, not a binding. A service answering several languages picks
// one per request instead, which the same validator serves concurrently:
//
//	msgs := r.LocalizedMessagesWith(catalogFor(req.Header.Get("Accept-Language")))
//
// Two limits are worth knowing before reaching for it. It does not change
// ValidationError.FriendlyMessage, which is always English — an error carries no
// locale, and the default travels on Result. And it does not reach the Validate
// family, which returns errors without a Result; localize those explicitly with
// Localizer.Localize.
//
// A nil argument is ignored, leaving the English default.
func WithLocalizer(l Localizer) Option {
	return func(cfg *validatorConfig) {
		cfg.localizer = l
	}
}

// WithOverride explicitly allows overriding one or more built-in validators
// in their respective namespace. Use WithOverrideMethod / WithOverrideFunc for
// namespace-specific overrides, or WithOverrideAll to allow overriding everything.
//
// Example:
//
//	// Override specific built-in methods
//	schemix.WithOverrideMethod("is_email", "luhn_valid")
//
//	// Override specific built-in functions
//	schemix.WithOverrideFunc("is_valid_date")
//
//	// Override everything — no conflict checks at all
//	schemix.WithOverrideAll()
func WithOverrideMethod(names ...string) Option {
	return func(cfg *validatorConfig) {
		cfg.allowMethodOverrides = append(cfg.allowMethodOverrides, names...)
	}
}

// WithOverrideFunc allows overriding specific built-in functions by name.
func WithOverrideFunc(names ...string) Option {
	return func(cfg *validatorConfig) {
		cfg.allowFuncOverrides = append(cfg.allowFuncOverrides, names...)
	}
}

// WithOverrideAll disables all built-in conflict checks — any name can be
// registered regardless of whether it conflicts with a built-in.
func WithOverrideAll() Option {
	return func(cfg *validatorConfig) {
		cfg.overrideAll = true
	}
}

// WithFunction registers a custom function using Bloblang's FunctionConstructor signature.
// This is the same signature as bloblang.RegisterFunction — a factory that receives
// arguments and returns a Function closure.
//
// Example:
//
//	v, _ := schemix.New(schema, schemix.WithFunction("is_even", func(args ...any) (bloblang.Function, error) {
//	    n, ok := args[0].(int64)
//	    if !ok {
//	        return nil, fmt.Errorf("is_even requires int64")
//	    }
//	    return func() (any, error) {
//	        return n%2 == 0, nil
//	    }, nil
//	}))
//
// In schema: check: bool @blob(is_even(this.amount))
func WithFunction(name string, fn bloblang.FunctionConstructor) Option {
	return func(cfg *validatorConfig) {
		if err := validateName(name); err != nil {
			cfg.funcMapErr = err
			return
		}
		cfg.customFuncs = append(cfg.customFuncs, customFuncEntry{
			name:   name,
			kind:   kindFuncV1,
			funcV1: fn,
		})
	}
}

// WithFunctionV2 registers a custom function using a PluginSpec for typed parameters.
// This matches Bloblang's RegisterFunctionV2 signature exactly.
//
// Example:
//
//	v, _ := schemix.New(schema, schemix.WithFunctionV2("calculate_fee",
//	    bloblang.NewPluginSpec().
//	        Param(bloblang.NewInt64Param("amount")).
//	        Param(bloblang.NewFloat64Param("rate")),
//	    func(args *bloblang.ParsedParams) (bloblang.Function, error) {
//	        amount, _ := args.GetInt64("amount")
//	        rate, _ := args.GetFloat64("rate")
//	        return func() (any, error) {
//	            return float64(amount) * rate, nil
//	        }, nil
//	    },
//	))
func WithFunctionV2(name string, spec *bloblang.PluginSpec, ctor bloblang.FunctionConstructorV2) Option {
	return func(cfg *validatorConfig) {
		if err := validateName(name); err != nil {
			cfg.funcMapErr = err
			return
		}
		cfg.customFuncs = append(cfg.customFuncs, customFuncEntry{
			name:   name,
			kind:   kindFuncV2,
			spec:   spec,
			funcV2: ctor,
		})
	}
}

// WithMethod registers a custom method using the simple style.
// Methods are called on a target value: this.field.my_method()
//
// Example:
//
//	v, _ := schemix.New(schema, schemix.WithMethod("is_valid_luhn", func(v any) (any, error) {
//	    s := v.(string)
//	    return luhnCheck(s), nil
//	}))
//
// In schema: check: bool @blob(this.pan.is_valid_luhn())
func WithMethod(name string, fn bloblang.Method) Option {
	return func(cfg *validatorConfig) {
		if err := validateName(name); err != nil {
			cfg.funcMapErr = err
			return
		}
		cfg.customFuncs = append(cfg.customFuncs, customFuncEntry{
			name: name,
			kind: kindMethodV1,
			methodV1: func(args ...any) (bloblang.Method, error) {
				return fn, nil
			},
		})
	}
}

// WithMethodV2 registers a custom method using a PluginSpec for typed parameters.
// This matches Bloblang's RegisterMethodV2 signature exactly.
//
// Example:
//
//	v, _ := schemix.New(schema, schemix.WithMethodV2("has_prefix_any",
//	    bloblang.NewPluginSpec().
//	        Param(bloblang.NewStringParam("prefixes").Description("comma-separated prefixes")),
//	    func(args *bloblang.ParsedParams) (bloblang.Method, error) {
//	        prefixes, _ := args.GetString("prefixes")
//	        parts := strings.Split(prefixes, ",")
//	        return func(v any) (any, error) {
//	            s := v.(string)
//	            for _, p := range parts {
//	                if strings.HasPrefix(s, p) { return true, nil }
//	            }
//	            return false, nil
//	        }, nil
//	    },
//	))
func WithMethodV2(name string, spec *bloblang.PluginSpec, ctor bloblang.MethodConstructorV2) Option {
	return func(cfg *validatorConfig) {
		if err := validateName(name); err != nil {
			cfg.funcMapErr = err
			return
		}
		cfg.customFuncs = append(cfg.customFuncs, customFuncEntry{
			name:     name,
			kind:     kindMethodV2,
			spec:     spec,
			methodV2: ctor,
		})
	}
}

// WithMaxSchemaDepth bounds how deep New() recurses while analysing the schema
// (nested structs, array element schemas and definitions).
//
// Exceeding the limit makes New() return an error rather than silently skipping
// the deeper levels: a skipped level could hide an @blob/@meta attribute that
// would then never be extracted, and a validator that quietly checks less than
// its schema declares is worse than one that refuses to build.
//
// n must be positive. The default is 32, which is far beyond any hand-written
// schema; raise it only for generated schemas with genuinely deep nesting.
func WithMaxSchemaDepth(n int) Option {
	return func(cfg *validatorConfig) {
		cfg.maxSchemaDepth = n
		cfg.maxSchemaDepthSet = true
	}
}

// resolveMaxSchemaDepth validates the configured limit, applying the default
// when the option was never set. A non-positive value is a configuration mistake
// rather than a request for unlimited recursion, so it is rejected — silently
// treating 0 as "unlimited" would reintroduce the non-termination this bound
// exists to prevent.
func resolveMaxSchemaDepth(configured int, set bool) (int, error) {
	if !set {
		return defaultMaxSchemaDepth, nil
	}
	if configured < 1 {
		return 0, fmt.Errorf("WithMaxSchemaDepth: depth must be positive, got %d", configured)
	}
	return configured, nil
}
